---
Description: "Effective DevOps in AWS: HelloWorld web application"
Outputs:
  InstancePublicIp:
    Description: "Public IP of our instance."
    Value: !GetAtt instance.PublicIp
  WebUrl:
    Description: "Application endpoint"
    Value: !Join
      - ""
      - - "http://"
        - !GetAtt instance.PublicDnsName
        - ":"
        - "3333"  # Updated port to 3333
Parameters:
  KeyPair:
    ConstraintDescription: "must be the name of an existing EC2 KeyPair."
    Description: "Name of an existing EC2 KeyPair to SSH"
    Type: "AWS::EC2::KeyPair::KeyName"
Resources:
  SecurityGroup:
    Properties:
      GroupDescription: "Allow SSH and TCP/3333 access"  # Updated description
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: "22"
          IpProtocol: "tcp"
          ToPort: "22"
        - CidrIp: "0.0.0.0/0"
          FromPort: "3333"  # Updated port to 3333
          IpProtocol: "tcp"
          ToPort: "3333"  # Updated port to 3333
    Type: "AWS::EC2::SecurityGroup"
  instance:
    Properties:
      ImageId: "ami-cfe4b2b0"
      InstanceType: "t2.nano"  # Updated instance type to T2.nano
      KeyName: !Ref KeyPair
      SecurityGroups:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Join
          - "\n"
          - - "#!/bin/bash"
            - "sudo yum install --enablerepo=epel -y nodejs"
            - "wget http://bit.ly/2vESNuc -O /home/ec2-user/helloworld.js"
            - "wget http://bit.ly/2vVvT18 -O /etc/init/helloworld.conf"
            - "start helloworld"
      Tags:
        - Key: "Name"
          Value: "HelloWorldInstance"
        - Key: "InstanceType"
          Value: "T2.nano"
    Type: "AWS::EC2::Instance"
