---
- name: Update Webserver and Install Database
  hosts: your_webserver_group  # Replace with the appropriate host or group from your inventory file
  become: yes  # Run tasks with elevated privileges

  tasks:
    - name: Copy new helloworld files
      copy:
        src: /path/to/your/helloworld/files
        dest: /var/www/html  # Replace with the actual path on your webserver
      notify:
        - Restart Apache  # Replace with the appropriate service restart task

    - name: Install MongoDB version 4.0
      yum:
        name: mongodb-org-4.0
        state: present
      notify:
        - Start MongoDB  # Replace with the appropriate service start task

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted

    - name: Start MongoDB
      service:
        name: mongod
        state: started
